version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports: ["5432:5432"]
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./demo_small.sql:/demo_small.sql
    restart: "no"
    shm_size: 1G
