/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package d5

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    Server().simpleServer(80)
}
