migrateup:
	migrate -path ./schema -database 'postgres://admin:admin@localhost:5432/postgres?sslmode=disable' up
migratedown:
	migrate -path ./schema -database 'postgres://admin:admin@localhost:5432/postgres?sslmode=disable' down
test:
	echo "testing make file"
